### ISSUE TITLE
Where is the backend ? 

### ISSUE THREAD

**Issue by AdeeshaP** [Siddharth-rajput2201/Home_Price_Predictor_App#1]
Did you make backend in flask ? Can you upload it ? Without deploying into Heroku, cant we use that locally?

**Comment by Siddharth-rajput2201** [comment]
Repository Link :  https://github.com/Siddharth-rajput2201/Home_Price_Predictor_Backend 

Yes the backend is made in flask ! 

Yes you run the server locally on your System

**Comment by AdeeshaP** [comment]
Hello Mr. Siddharth,

I tried your code and did some modifications as per the same requirements of my project. For that I want to get the lowest price of the given location also. The modified code is given below and the output is given as expected in jupyter notebook. 

def predict_price(location,sqft,bath,bhk) :  
        loc_index = np.where(X.columns==location)[0][0]
        x = np.zeros(len(X.columns))
        x[0] = sqft
        x[1] = bath
        x[2] = bhk
        if loc_index >= 0:
            x[loc_index] = 1
        df_new = df12[df12[location] == 1]    
        predictprice = lr_clf.predict([x])[0]
        lowest_price = df_new['price'].min()
        return predictprice, lowest_price

*****************************************************
predict_price('1st Phase JP Nagar',1000, 2, 2)

The output : (83.49904677178024, 50.0)

Could you please tell me how to do modifications from Flask API in util.py and app.py for retrieving predicted price and lowest price also. ?
